name = "api-support"
main = "worker-checker.js"
compatibility_date = "2024-03-26"
minify = true

[vars]
HEALTH_CHECK_TIMEOUT = "5000"
SLAVE_TOKEN = "slave"
MASTER_CALLBACK = "https://api-master.dongtelo75.workers.dev/submit-results"
MASTER_TOKEN = "master"

[[kv_namespaces]]
binding = "PROXY_CACHE"
id = "8865cddc913b4df196dcbdeff3c31fe1"

[[kv_namespaces]]
binding = "GEO_CACHE"
id = "b5b734e450574fd98ef831d33731da87"
